# Generated by Django 5.2.6 on 2025-10-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_petition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='text',
        ),
    ]
