# Generated by Django 5.2.6 on 2025-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_petition_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
