# Generated by Django 5.2.6 on 2025-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_petition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_petitioned',
            field=models.BooleanField(default=False),
        ),
    ]
